export const CLIM_PROTOCOL_ABI = [
  {
    type: 'function',
    name: 'getProtocolStats',
    inputs: [],
    outputs: [
      { name: 'totalLiquidity', type: 'uint256' },
      { name: 'availableLiquidity', type: 'uint256' },
      { name: 'activeEvents', type: 'uint256' },
      { name: 'version', type: 'string' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getEventDetails',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [
      {
        name: 'eventData',
        type: 'tuple',
        components: [
          { name: 'latitude', type: 'int256' },
          { name: 'longitude', type: 'int256' },
          { name: 'startTime', type: 'uint256' },
          { name: 'endTime', type: 'uint256' },
          { name: 'thresholdMm', type: 'uint256' },
          { name: 'payoutPerToken', type: 'uint256' },
          { name: 'totalSupply', type: 'uint256' },
          { name: 'actualMm', type: 'uint256' },
          { name: 'status', type: 'uint8' },
        ],
      },
      { name: 'availableTokens', type: 'uint256' },
      { name: 'currentPremium', type: 'uint256' },
      { name: 'isSettled', type: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getUserPortfolio',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [
      { name: 'eventIds', type: 'uint256[]' },
      { name: 'tokenBalances', type: 'uint256[]' },
      { name: 'potentialPayouts', type: 'uint256[]' },
      { name: 'canRedeem', type: 'bool[]' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'quickBuy',
    inputs: [
      { name: 'eventId', type: 'uint256' },
      { name: 'tokenAmount', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'provideLiquidity',
    inputs: [],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'batchRedeemTokens',
    inputs: [{ name: 'eventIds', type: 'uint256[]' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getContractAddresses',
    inputs: [],
    outputs: [
      { name: 'tokenContract', type: 'address' },
      { name: 'factoryContract', type: 'address' },
      { name: 'poolContract', type: 'address' },
      { name: 'settlementContract', type: 'address' },
      { name: 'oracleContract', type: 'address' },
    ],
    stateMutability: 'view',
  },
] as const;
